# Global context is empty, only server blocks allowed

server {
    listen localhost:9090;
    server_name example.com;

    client_max_body_size 5M;
    mime_types text/markdown  md application/wasm wasm;
    
    # Default root for this server
    root ./www/cgi-bin;
    
    # Default index
    index index.html;
    # error_page 404 505 error.html;

    # A specific route
	location / {
        root ./www/post;
        allow_methods POST GET;
	}
    location /images {
        root ./www/post;
        allow_methods POST GET;
	}
}
