server {
    listen localhost:9090;
    server_name example.com;

    client_max_body_size 10G;
    mime_types text/markdown  md application/wasm wasm;
    
    root ./www/cgi-bin;
	 
    # index index.html;

	location / {
		root ./www/html/;
		allow_methods GET;
	}

	location /cgi {
        allow_methods POST GET;
		auto_index on;
		root ./www/cgi-bin;
		cgi_pass .py /bin/python3;
		cgi_pass .sh /usr/bin/bash;
	}

    location /post {
		root /goinfre/lazmoud/;
		auto_index on;
        allow_methods POST DELETE GET;
	}
}
