# Global context is empty, only server blocks allowed

server {
    listen localhost:8080;
    server_name example.com;

    client_max_body_size 5M;
    mime_types text/markdown  md application/wasm wasm;
    
    # Default root for this server
    root /var/www/html;
    auto_index on;
    
    # Default index
    index index.html;
    error_page 404 505 error.html;

    # A specific route
    location /images {
        root /var/www/images;
        index index.py;
        auto_index on;
        allow_methods POST GET;
        cgi_pass .py /usr/bin/python;
        return /luna;
    }

    location /html {
        root ./www;
        index index.html;
        auto_index on;
        allow_methods POST GET;
    }

    location /api {
        # This one has no specific root, inherits from server? 
        # (Logic depends on your implementation, parser just stores it)
        index api.json;
    }

    location /test {
        
    }
}

server {
    listen localhost:8000;
    server_name example.com;

    client_max_body_size 5M;
    
    # Default root for this server
    root /var/www/html;
    
    # Default index
    index index.html;
    error_page 404 505 error.html;

    # A specific route
    location /images {
        root /var/www/images;
        index gallery.html;
        auto_index on;
        allow_methods POST GET;
        cgi_pass .py /usr/bin/python;
        return /luna;
    }

    location / {
        root /var/www/images;
        index gallery.html;
        auto_index on;
        allow_methods DELETE;
        cgi_pass .py /usr/bin/python;
        return /luna;
    }
}


server {
    listen localhost:9000;
    auto_index on;
    root .;
    auto_index on;
	location / {
		allow_methods GET;
		cgi_pass .py /bin/python3;
	}
}
