# Global context is empty, only server blocks allowed

server {
    listen localhost:8080;
    server_name example.com;

    client_max_body_size 5M;
    
    # Default root for this server
    root /var/www/html;
    
    # Default index
    index index.html;
    error_page 404 305 error.html;

    # A specific route
    location /images {
        root /var/www/images;
        index gallery.html;
        auto_index on;
        allow_methods POST GET;
        cgi_pass bypass.py /usr/bin/python;
        return /luna;
    }

    location /api {
        # This one has no specific root, inherits from server? 
        # (Logic depends on your implementation, parser just stores it)
        index api.json;
    }
}

server {
    listen localhost:9090;
    server_name test.com;
    root /tmp/test;
    
    location / {
        index home.html;
    }
}