name: C/C++ CI

on:
  push:
    branches: [ "master", "request-parsing" ]
  pull_request:
    branches: [ "master", "request-parsing" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ make
    
    - name: Build
      run: make
    
    - name: Clean
      run: make clean